/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MTokenRouteImport } from './routes/m.$token'
import { Route as MixTokenRouteImport } from './routes/mix.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MTokenRoute = MTokenRouteImport.update({
  id: '/m/$token',
  path: '/m/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MixTokenRoute = MixTokenRouteImport.update({
  id: '/mix/$token',
  path: '/mix/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/m/$token': typeof MTokenRoute
  '/mix/$token': typeof MixTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/m/$token': typeof MTokenRoute
  '/mix/$token': typeof MixTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/m/$token': typeof MTokenRoute
  '/mix/$token': typeof MixTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/m/$token' | '/mix/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/m/$token' | '/mix/$token'
  id: '__root__' | '/' | '/m/$token' | '/mix/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MTokenRoute: typeof MTokenRoute
  MixTokenRoute: typeof MixTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$token': {
      id: '/m/$token'
      path: '/m/$token'
      fullPath: '/m/$token'
      preLoaderRoute: typeof MTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mix/$token': {
      id: '/mix/$token'
      path: '/mix/$token'
      fullPath: '/mix/$token'
      preLoaderRoute: typeof MixTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MTokenRoute: MTokenRoute,
  MixTokenRoute: MixTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
